distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.4.0
install_time: "Thu Nov 29 20:53:44 2018"
installation_id: "61fc3692-e9a9-4602-9091-d350c34c881d"
rime_version: 1.4.0
update_time: "Sat Jun 15 10:30:51 2019"